name: Deploy to EC2

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run lint check
      run: npm run lint || true
    
    - name: Build check
      run: npm run build

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Copy files to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: ${{ secrets.EC2_PORT }}
        source: "."
        target: "/home/ubuntu/app"
        strip_components: 0

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: ${{ secrets.EC2_PORT }}
        script: |
           # Update system
           sudo yum update -y
           
           # Install Node.js if not installed
           if ! command -v node &> /dev/null; then
             curl -fsSL https://rpm.nodesource.com/setup_18.x | sudo bash -
             sudo yum install -y nodejs
           fi
           
           # Install PM2 for process management
           if ! command -v pm2 &> /dev/null; then
             sudo npm install -g pm2
           fi
           
           # Navigate to app directory
           cd /home/ec2-user/app
           
           # Stop existing process if running
           pm2 stop labcellbio-backend || true
           pm2 delete labcellbio-backend || true
           
           # Install dependencies
           npm ci --production
           
           # Build the application
           npm run build
           
           # Create .env file
           cat > .env << 'EOF'
           DB_HOST=${{ secrets.DB_HOST }}
           DB_PORT=${{ secrets.DB_PORT }}
           DB_USERNAME=${{ secrets.DB_USERNAME }}
           DB_PASSWORD=${{ secrets.DB_PASSWORD }}
           DB_DATABASE=${{ secrets.DB_DATABASE }}
           JWT_SECRET=${{ secrets.JWT_SECRET }}
           JWT_EXPIRES_IN=${{ secrets.JWT_EXPIRES_IN }}
           AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
           AWS_REGION=${{ secrets.AWS_REGION }}
           AWS_S3_BUCKET=${{ secrets.AWS_S3_BUCKET }}
           EOF
           
           # Start application with PM2
           pm2 start dist/main.js --name labcellbio-backend --env production
           
           # Save PM2 configuration
           pm2 save
           
           # Setup PM2 to start on boot
           pm2 startup
           
           # Show logs
           pm2 logs labcellbio-backend --lines 20 